language:
  - node_js
  - ruby
node_js:
  - 5
install:
  - travis_retry gem install s3_website -v 3.4.0
  - travis_retry npm install
before_script: webpack
script:
  - "npm run test"
  - ./s3_deploy.sh
cache:
  bundler: true
  directories:
    - node_modules
